services:
  database_sql:
    image: 'postgres:latest'
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: username # The PostgreSQL user (useful to connect to the database)
      POSTGRES_PASSWORD: password # The PostgreSQL password (useful to connect to the database)
      POSTGRES_DB: default_database # The PostgreSQL default database (automatically created at first launch)
    env_file:
      - .env
    volumes:
      - ${PWD}/init.sql:/docker-entrypoint-initdb.d/init.sql
  
  database_nosql:
    image: neo4j:latest
    volumes:  
      - /$HOME/neo4j/logs:/logs
      - /$HOME/neo4j/config:/config
      - /$HOME/neo4j/data:/data
      - /$HOME/neo4j/plugins:/plugins
    environment:
      - NEO4J_AUTH=neo4j/your_password 
    ports:
      - "7474:7474"
      - "7687:7687"
    restart: always

  website:
    build: .